app/plan/models/plan.py
# -*- coding: utf-8 -*-
from datetime import datetime
from init_app import db

class BaseModel(db.Model):
    """基类模型
    """
    __abstract__ = True

    add_date = db.Column(db.DateTime, nullable=True, default=datetime.now) # 创建时间
    pub_date = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now, nullable=True) # 更新时间


class PlanList(BaseModel):
    """大目标
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(240), nullable=False) # 标题
    description = db.Column(db.String(240), nullable=False) # 描述
    startTime = db.Column(db.DateTime, nullable=False) # 开始时间
    deadLineTime = db.Column(db.DateTime, nullable=False) # 结束时间
    createBy = db.Column(db.Integer, nullable=False) # 创建人

    def __repr__(self):
        return '<Title: %r>' % self.title
    
class Plan(BaseModel):
    """小目标
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(240), nullable=False) # 标题
    description = db.Column(db.String(240), nullable=False) # 描述
    startTime = db.Column(db.DateTime, nullable=False) # 开始时间
    deadLineTime = db.Column(db.DateTime, nullable=False) # 结束时间
    completedStatus = db.Column(db.Integer, nullable=False) # 是否已完成：1、已完成；0、未完成
    createBy = db.Column(db.Integer, nullable=False) # 创建人
    belongTo = db.Column(db.Integer, nullable=False) # 属于哪个PlanList

    def __repr__(self):
        return '<Title: %r>' % self.title

app/plan/views/plan.py
# -*- coding: utf-8 -*-
from ..models import Plan, PlanList
from app.auth.views.auth import login_required
from init_app import db

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from datetime import datetime


bp = Blueprint(
    "plan",
    __name__,
    url_prefix="/plan",
    template_folder="../templates",
    static_folder="../static",
)


@bp.route("/")
@login_required
def index():
    """
    主页
    """
    page = request.args.get("page", 1, type=int)

    # 查询出此用户创建的所有PlanList
    # 按照结束时间进行排序
    # 利用paginate进行分页，每页7条记录
    pagination = (
        PlanList.query.filter_by(createBy=session.get("user_id"))
        .order_by(PlanList.deadLineTime)
        .paginate(page=page, per_page=7, error_out=False)
    )

    # 获取到当前分页的内容pagination.items
    planList_List = pagination.items

    # 用分页器和分页内容去渲染模板
    return render_template(
        "planList.html", planLists=planList_List, pagination=pagination
    )


@bp.route("/addList", methods=(["POST"]))
@login_required
def add_list():
    flashDict = {}
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]

        # 对前端回传的字符串形式的时间进行格式化，转换成datetime对象用于传入数据库
        startTime = datetime.strptime(request.form["startTime"], "%Y-%m-%d").date()
        deadLineTime = datetime.strptime(
            request.form["deadLineTime"], "%Y-%m-%d"
        ).date()

        createBy = session.get("user_id")
        error = None

        # 到数据库中查重
        planList_tmp = PlanList.query.filter_by(title=title, createBy=createBy).first()

        if planList_tmp:
            error = f"此主题：“{title}”已经存在了！"
        elif not title:
            error = "标题不能为空！"
        elif startTime > deadLineTime:
            error = "结束时间不能早于起始时间！"
        if error == None:
            try:
                planList = PlanList(
                    title=title,
                    description=description,
                    startTime=startTime,
                    deadLineTime=deadLineTime,
                    createBy=createBy,
                )
                db.session.add(planList)
                db.session.commit()
            except Exception as e:
                error = f"计划列表：“{title}”添加失败。"
                db.session.rollback()
            else:
                flashDict["success"] = "添加计划列表成功"
        flashDict["error"] = error
        flash(flashDict)
    return redirect(url_for("plan.index"))


@bp.route("/delPlanList/<int:planList_id>", methods=["GET", "POST"])
@login_required
def del_list(planList_id):
    '''
    按指定的planList_id进行删除

    参数
    ----
    planList_id
        要删除的PlanList的id
    '''
    flashDict = {}
    planList = PlanList.query.filter_by(
        id=planList_id, createBy=session.get("user_id")
    ).first()
    if planList:
        db.session.delete(planList)
        db.session.commit()
        flashDict["success"] = f"{planList.title}删除成功"
        flash(flashDict)
        return redirect(url_for("plan.index"))


@bp.route("/updatePlanList/<int:planList_id>", methods=["POST"])
@login_required
def update_list(planList_id):
    '''
    按指定的planList_id进行更新删除

    参数
    ----
    planList_id
        要更新的PlanList的id

    TODO
    ----
    尝试着用update方法结果报错了，只能使用先删除再新增的方式去操作，这里应该可以优化的
    '''
    flashDict = {}
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]

        # 对前端回传的字符串形式的时间进行格式化，转换成datetime对象用于传入数据库
        startTime = datetime.strptime(request.form["startTime"], "%Y-%m-%d").date()
        deadLineTime = datetime.strptime(
            request.form["deadLineTime"], "%Y-%m-%d"
        ).date()
        createBy = session.get("user_id")
        error = None

        planList_tmp = PlanList.query.filter_by(
            id=planList_id, createBy=createBy
        ).first()
        if planList_tmp.title != title:
            planList_tmp2 = PlanList.query.filter_by(
                title=title, createBy=createBy
            ).first()
            if planList_tmp2:
                error = f"此主题：“{title}”已经存在了！"
        elif not title:
            error = "标题不能为空！"
        elif startTime > deadLineTime:
            error = "结束时间不能早于起始时间！"
        if error == None:
            try:
                planList = PlanList(
                    id=planList_id,
                    title=title,
                    description=description,
                    startTime=startTime,
                    deadLineTime=deadLineTime,
                    createBy=createBy,
                )
                db.session.delete(
                    PlanList.query.filter_by(
                        id=planList_id, createBy=session.get("user_id")
                    ).first()
                )
                db.session.add(planList)
                db.session.commit()
            except Exception as e:
                error = f"计划列表：“{title}”修改失败。"
                db.session.rollback()
            else:
                flashDict["success"] = "修改计划列表成功"
        flashDict["error"] = error
        flash(flashDict)
    return redirect(url_for("plan.index"))


@bp.route("/plans/<int:planList_id>")
@login_required
def sel_plans(planList_id):
    '''
    进入PlanList之后的主页，基本思路和PlanList一样，这里偷懒了
    '''
    planList = PlanList.query.filter_by(
        createBy=session.get("user_id"), id=planList_id
    ).first()
    page = request.args.get("page", 1, type=int)
    pagination = (
        Plan.query.filter_by(createBy=session.get("user_id"), belongTo=planList_id)
        .order_by(Plan.completedStatus, Plan.deadLineTime, Plan.title)
        .paginate(page=page, per_page=7, error_out=False)
    )
    plan_List = pagination.items
    return render_template(
        "plans.html", plans=plan_List, planList=planList, pagination=pagination
    )


@bp.route("/addPlan/<int:planList_id>", methods=(["POST"]))
@login_required
def add_plan(planList_id):
    '''
    新增Plan
    '''
    flashDict = {}
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        startTime = datetime.strptime(request.form["startTime"], "%Y-%m-%d").date()
        deadLineTime = datetime.strptime(
            request.form["deadLineTime"], "%Y-%m-%d"
        ).date()
        createBy = session.get("user_id")
        belongTo = planList_id

        error = None

        planList_tmp = PlanList.query.filter_by(id=planList_id).first()
        plan_tmp = Plan.query.filter_by(title=title, createBy=createBy).first()
        if plan_tmp:
            error = f"此主题：“{title}”已经存在了！"
        elif not title:
            error = "标题不能为空！"
        elif (
            startTime < planList_tmp.startTime.date()
            or deadLineTime > planList_tmp.deadLineTime.date()
        ):
            error = "计划的时间范围超过了计划列表的时间范围！"
        elif startTime > deadLineTime:
            error = "结束时间不能早于起始时间！"
        if error == None:
            try:
                plan = Plan(
                    title=title,
                    description=description,
                    startTime=startTime,
                    deadLineTime=deadLineTime,
                    createBy=createBy,
                    belongTo=belongTo,
                    completedStatus=0,
                )
                db.session.add(plan)
                db.session.commit()
            except Exception as e:
                error = f"计划：“{title}”添加失败。"
                db.session.rollback()
            else:
                flashDict["success"] = "添加计划成功"
        flashDict["error"] = error
        flash(flashDict)
    return redirect(url_for("plan.sel_plans", planList_id=planList_id))


@bp.route("/delPlan/<int:planList_id>/<int:plan_id>", methods=["GET", "POST"])
@login_required
def del_plan(planList_id, plan_id):
    '''
    删除Plan
    '''
    flashDict = {}
    plan = Plan.query.filter_by(id=plan_id, createBy=session.get("user_id")).first()
    if plan:
        db.session.delete(plan)
        db.session.commit()
        flashDict["success"] = f"{plan.title}删除成功"
        flash(flashDict)
        return redirect(
            url_for("plan.sel_plans", planList_id=planList_id, plan_id=plan_id)
        )


@bp.route("/updatePlan/<int:planList_id>/<int:plan_id>", methods=["POST"])
@login_required
def update_plan(planList_id, plan_id):
    '''
    编辑Plan
    '''
    flashDict = {}
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        startTime = datetime.strptime(request.form["startTime"], "%Y-%m-%d").date()
        deadLineTime = datetime.strptime(
            request.form["deadLineTime"], "%Y-%m-%d"
        ).date()
        createBy = session.get("user_id")
        belongTo = planList_id
        error = None

        planList_tmp = PlanList.query.filter_by(id=planList_id).first()
        plan_tmp = Plan.query.filter_by(id=plan_id, createBy=createBy).first()
        if plan_tmp.title != title:
            plan_tmp2 = Plan.query.filter_by(title=title, createBy=createBy).first()
            if plan_tmp2:
                error = f"此主题：“{title}”已经存在了！"
        elif not title:
            error = "标题不能为空！"
        elif (
            startTime < planList_tmp.startTime.date()
            or deadLineTime > planList_tmp.deadLineTime.date()
        ):
            error = "计划的时间范围超过了计划列表的时间范围！"
        elif startTime > deadLineTime:
            error = "结束时间不能早于起始时间！"
        if error == None:
            try:
                plan = Plan(
                    id=plan_id,
                    title=title,
                    description=description,
                    startTime=startTime,
                    deadLineTime=deadLineTime,
                    createBy=createBy,
                    belongTo=belongTo,
                    completedStatus=plan_tmp.completedStatus,
                )
                db.session.delete(

app/plan/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="main-panel py-5">
    <div class="content-wrapper">
            {% block main_content %}
            {% endblock %}
    </div>
</div>

{% endblock %}

app/plan/templates/planList.html
{% extends 'index.html' %}

{% block title %} - 计划列表 {% endblock title %}

{% block extra_header %}
<link rel="stylesheet" href="{{ url_for('plan.static', filename='css/bootstrap-datetimepicker.min.css') }}">
{% endblock %}

{% block main_content %}
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-3  d-flex justify-content-center justify-content-center">
        <div class="card mb-3 flex-fill">
          <div class="card-body d-flex justify-content-center">
            <button type="button" class="btn btn-primary align-self-center" data-toggle="modal" data-target="#staticBackdrop">
              新建计划列表
            </button>
            <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
              aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新建计划列表</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form class="pt-3 w-100 " method="post" action="{{ url_for('plan.add_list') }}">
                    <div class="modal-body">
                      <div class="form-group">
                        <label for="title">主题</label>
                        <input type="text" class="form-control form-control-lg" id="title" placeholder="主题" name="title"
                          required="required">
                      </div>
                      <div class="form-group">
                        <label for="description">描述</label>
                        <textarea type="text" class="form-control form-control-lg" style="height: 100px;resize: none;"
                          id="description" placeholder="描述" name="description" required="required"></textarea>
                      </div>
                      <div class="form-group">
                        <label for="startTime">起始时间</label>
                        <input type="text" class="form-control form-control-lg" id="startTime" placeholder="XXXX-XX-XX"
                          name="startTime" required="required">
                      </div>
                      <div class="form-group">
                        <label for="deadLineTime">结束时间</label>
                        <input type="text" class="form-control form-control-lg" id="deadLineTime"
                          placeholder="XXXX-XX-XX" name="deadLineTime" required="required">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <input class="btn btn-primary font-weight-medium" type="submit" value="提交">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% for planList in planLists %}
      <div class="col-md-3">
        <div class="card mb-3 shadow-sm">
          <h5 class="card-header font-weight-bold"><a href="{{ url_for('plan.sel_plans', planList_id=planList.id) }}" class="card-link mr-auto">{{ planList.title }}</a></h5>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">{{ planList.startTime.strftime("%Y-%m-%d")+" ~ "+planList.deadLineTime.strftime("%Y-%m-%d") }}</h6>
            <p class="card-text overflow-auto" style="height: 100px;">{{ planList.description }}</p>
            
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateBackdrop{{ planList.id }}">
              编辑
            </button>
            <div class="modal fade" id="updateBackdrop{{ planList.id }}" data-backdrop="static" data-keyboard="false" tabindex="-1"
              aria-labelledby="updateBackdropLabel{{ planList.id }}" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="updateBackdropLabel{{ planList.id }}">编辑</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form class="pt-3 w-100 " method="post"
                    action="{{ url_for('plan.update_list', planList_id=planList.id) }}">
                    <div class="modal-body">
                      <div class="form-group">
                        <label for="title">主题</label>
                        <input type="text" class="form-control form-control-lg" id="title" placeholder="主题" name="title"
                          required="required" value="{{ planList.title }}">
                      </div>
                      <div class="form-group">
                        <label for="description">描述</label>
                        <textarea type="text" class="form-control form-control-lg" style="height: 100px;resize: none;"
                          id="description" placeholder="描述" name="description"
                          required="required">{{ planList.description }}</textarea>
                      </div>
                      <div class="form-group">
                        <label for="startTime">起始时间</label>
                        <input type="text" class="form-control form-control-lg" id="startTime{{ planList.id }}" placeholder="XXXX-XX-XX"
                          name="startTime" required="required" value="{{ planList.startTime }}">
                      </div>
                      <div class="form-group">
                        <label for="deadLineTime">结束时间</label>
                        <input type="text" class="form-control form-control-lg" id="deadLineTime{{ planList.id }}"
                          placeholder="XXXX-XX-XX" name="deadLineTime" required="required"
                          value="{{ planList.deadLineTime }}">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <input class="btn btn-primary font-weight-medium" type="submit" value="提交">
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteBackdrop{{ planList.id }}">
              删除
            </button>
            <div class="modal fade" id="deleteBackdrop{{ planList.id }}" data-backdrop="static" data-keyboard="false" tabindex="-1"
              aria-labelledby="deleteBackdropLabel{{ planList.id }}" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteBackdroppLabel{{ planList.id }}">删除</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form class="pt-3 w-100 " method="post"
                    action="{{ url_for('plan.del_list', planList_id=planList.id) }}">
                    <div class="modal-body">
                      <div class="form-group">
                        <p>您确定要删除计划列表<label class="font-weight-bold">“{{ planList.title }}”</label>么?</p>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <input class="btn btn-primary font-weight-medium" type="submit" value="确定">
                    </div>
                  </form>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>



<div class="container fixed-bottom">
  <div class="row d-flex justify-content-center">
  <nav aria-label="pagination">
    <ul class="pagination pagination-lg">
    {% if pagination.has_prev %}
    <li class="page-item"><a href="{{ url_for('plan.index') }}?page={{ pagination.prev_num }}" class="page-link">上一页</a>
    </li>
    {% else %}
    <li class="page-item disabled"><a href="#" class="page-link">上一页</a>
    </li>
    {% endif %}
    

      {% for page in pagination.iter_pages() %}
      {% if page %}
      {% if page != pagination.page %}
      <li class="page-item">
        <a href="{{ url_for('plan.index') }}?page={{ page }}" class="page-link" aria-label="Page 1"
          aria-current="page">{{ page }}</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
      </li>
      {% endif %}
      {% else %}
      <span class="pagination-ellipsis">&hellip;</span>
      {% endif %}
      {% endfor %}

      {% if pagination.has_next %}
    <li class="page-item"><a href="{{ url_for('plan.index') }}?page={{ pagination.next_num }}" class="page-link">下一页</a>
    </li>
    {% else %}
    <li class="page-item disabled"><a href="#" class="page-link">下一页</a>
    </li>
    {% endif %}

    </ul>
  </nav>
  </div>
  <div class="row d-flex justify-content-center">
    <p class="text-white">小朱 2024.05</p>
  </div>
  </div>


{% endblock %}

{% block extra_script %}
<script src="{{ url_for('plan.static', filename='js/moment.js') }}"></script>
<script src="{{ url_for('plan.static', filename='js/bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript">
  $(function () {
    $('#startTime').datetimepicker({
      format: 'YYYY-MM-DD',
    });
  });
  $(function () {
    $('#deadLineTime').datetimepicker({
      format: 'YYYY-MM-DD',
      MinDate: $('#startTime').datetimepicker.Value
    });
  });

  $("input[id^='startTime']").each(function () {
    $(this).datetimepicker({format: 'YYYY-MM-DD',});
})
$("input[id^='deadLineTime']").each(function () {
    $(this).datetimepicker({format: 'YYYY-MM-DD',});
})
  
</script>
{% endblock %}